name: Async Build Script
on:
  push: { }
  pull_request: { }
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 22
          java-package: jdk

      - name: Install required dependencies
        run: sudo apt update && sudo apt install libtinfo5

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle/loom-cache
          key: ${{ runner.os }}-gradle4-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle4-

      - name: Build Async
        run: |
          ./gradlew clean processIncludeJars build --stacktrace

      - name: Prepare artifact directory
        run: |
          mkdir jars
          cp neoforge/build/libs/*.jar jars/
          cp fabric/build/libs/*.jar jars/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: async-artifacts
          path: jars/*.jar